import type { ThemeDefinition } from '@/types/theme'

export const dracula: ThemeDefinition = {
  id: 'dracula',
  name: 'Dracula',
  type: 'dark',
  colors: {
    '--background': '#282a36',
    '--foreground': '#f8f8f2',
    '--card': '#21222c',
    '--card-foreground': '#f8f8f2',
    '--popover': '#21222c',
    '--popover-foreground': '#f8f8f2',
    '--primary': '#bd93f9',
    '--primary-foreground': '#282a36',
    '--secondary': '#44475a',
    '--secondary-foreground': '#f8f8f2',
    '--muted': '#44475a',
    '--muted-foreground': '#6272a4',
    '--accent': '#44475a',
    '--accent-foreground': '#f8f8f2',
    '--destructive': '#ff5555',
    '--border': 'rgba(255, 255, 255, 0.1)',
    '--input': 'rgba(255, 255, 255, 0.15)',
    '--ring': '#bd93f9',
    '--df-success': '#50fa7b',
    '--df-warning': '#f1fa8c',
    '--df-info': '#8be9fd',
    '--df-elevated': '#44475a',
    '--df-surface': '#21222c',
    '--df-overlay': 'rgba(0, 0, 0, 0.6)',
    '--sidebar': '#21222c',
    '--sidebar-foreground': '#f8f8f2',
    '--sidebar-primary': '#bd93f9',
    '--sidebar-primary-foreground': '#282a36',
    '--sidebar-accent': '#44475a',
    '--sidebar-accent-foreground': '#f8f8f2',
    '--sidebar-border': 'rgba(255, 255, 255, 0.1)',
    '--sidebar-ring': '#bd93f9',
  },
  editor: {
    base: 'vs-dark',
    rules: [
      { token: 'comment', foreground: '6272a4', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'ff79c6' },
      { token: 'string', foreground: 'f1fa8c' },
      { token: 'number', foreground: 'bd93f9' },
      { token: 'type', foreground: '8be9fd', fontStyle: 'italic' },
      { token: 'identifier', foreground: 'f8f8f2' },
      { token: 'delimiter', foreground: 'f8f8f2' },
      { token: 'operator', foreground: 'ff79c6' },
      { token: 'predefined', foreground: '50fa7b' },
    ],
    colors: {
      'editor.background': '#282a36',
      'editor.foreground': '#f8f8f2',
      'editor.lineHighlightBackground': '#44475a',
      'editor.selectionBackground': '#44475a',
      'editorCursor.foreground': '#f8f8f0',
      'editorLineNumber.foreground': '#6272a4',
      'editorLineNumber.activeForeground': '#f8f8f2',
    },
  },
  terminal: {
    background: '#282a36',
    foreground: '#f8f8f2',
    cursor: '#f8f8f0',
    selectionBackground: '#44475a',
    black: '#21222c',
    red: '#ff5555',
    green: '#50fa7b',
    yellow: '#f1fa8c',
    blue: '#bd93f9',
    magenta: '#ff79c6',
    cyan: '#8be9fd',
    white: '#f8f8f2',
    brightBlack: '#6272a4',
    brightRed: '#ff6e6e',
    brightGreen: '#69ff94',
    brightYellow: '#ffffa5',
    brightBlue: '#d6acff',
    brightMagenta: '#ff92df',
    brightCyan: '#a4ffff',
    brightWhite: '#ffffff',
  },
}
