import type { ThemeDefinition } from '@/types/theme'

export const nord: ThemeDefinition = {
  id: 'nord',
  name: 'Nord',
  type: 'dark',
  colors: {
    '--background': '#2e3440',
    '--foreground': '#d8dee9',
    '--card': '#3b4252',
    '--card-foreground': '#d8dee9',
    '--popover': '#3b4252',
    '--popover-foreground': '#d8dee9',
    '--primary': '#88c0d0',
    '--primary-foreground': '#2e3440',
    '--secondary': '#3b4252',
    '--secondary-foreground': '#d8dee9',
    '--muted': '#3b4252',
    '--muted-foreground': '#7b88a1',
    '--accent': '#434c5e',
    '--accent-foreground': '#d8dee9',
    '--destructive': '#bf616a',
    '--border': 'rgba(255, 255, 255, 0.08)',
    '--input': 'rgba(255, 255, 255, 0.12)',
    '--ring': '#88c0d0',
    '--df-success': '#a3be8c',
    '--df-warning': '#ebcb8b',
    '--df-info': '#81a1c1',
    '--df-elevated': '#434c5e',
    '--df-surface': '#3b4252',
    '--df-overlay': 'rgba(0, 0, 0, 0.5)',
    '--sidebar': '#3b4252',
    '--sidebar-foreground': '#d8dee9',
    '--sidebar-primary': '#88c0d0',
    '--sidebar-primary-foreground': '#2e3440',
    '--sidebar-accent': '#434c5e',
    '--sidebar-accent-foreground': '#d8dee9',
    '--sidebar-border': 'rgba(255, 255, 255, 0.08)',
    '--sidebar-ring': '#88c0d0',
  },
  editor: {
    base: 'vs-dark',
    rules: [
      { token: 'comment', foreground: '616e88', fontStyle: 'italic' },
      { token: 'keyword', foreground: '81a1c1' },
      { token: 'string', foreground: 'a3be8c' },
      { token: 'number', foreground: 'b48ead' },
      { token: 'type', foreground: '8fbcbb' },
      { token: 'identifier', foreground: 'd8dee9' },
      { token: 'delimiter', foreground: 'eceff4' },
      { token: 'operator', foreground: '81a1c1' },
      { token: 'predefined', foreground: '88c0d0' },
    ],
    colors: {
      'editor.background': '#2e3440',
      'editor.foreground': '#d8dee9',
      'editor.lineHighlightBackground': '#3b4252',
      'editor.selectionBackground': '#434c5e',
      'editorCursor.foreground': '#d8dee9',
      'editorLineNumber.foreground': '#4c566a',
      'editorLineNumber.activeForeground': '#d8dee9',
    },
  },
  terminal: {
    background: '#2e3440',
    foreground: '#d8dee9',
    cursor: '#d8dee9',
    selectionBackground: '#434c5e',
    black: '#3b4252',
    red: '#bf616a',
    green: '#a3be8c',
    yellow: '#ebcb8b',
    blue: '#81a1c1',
    magenta: '#b48ead',
    cyan: '#88c0d0',
    white: '#e5e9f0',
    brightBlack: '#4c566a',
    brightRed: '#bf616a',
    brightGreen: '#a3be8c',
    brightYellow: '#ebcb8b',
    brightBlue: '#81a1c1',
    brightMagenta: '#b48ead',
    brightCyan: '#8fbcbb',
    brightWhite: '#eceff4',
  },
}
