import type { QueryResult } from '@/types/database'
// --- 导出工具类（增强专业版） ---

/** 获取当前时间格式化字符串 */
function getTimestamp(): string {
  return new Date().toLocaleString('zh-CN', { 
    year: 'numeric', month: '2-digit', day: '2-digit', 
    hour: '2-digit', minute: '2-digit', second: '2-digit' 
  })
}

function escapeCSV(value: unknown): string {
  if (value === null || value === undefined) return ''
  const str = String(value)
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`
  }
  return str
}

/** 将查询结果转换为 CSV 格式，包含 UTF-8 BOM 以兼容 Excel */
export function toCSV(result: QueryResult): string {
  const header = result.columns.map((c) => escapeCSV(c.name)).join(',')
  const rows = result.rows.map((row) => row.map((v) => escapeCSV(v)).join(','))
  
  // \uFEFF 是 UTF-8 BOM，确保 Excel 打开不乱码
  return '\uFEFF' + [header, ...rows].join('\n')
}

/** 将查询结果转换为专业的 JSON 格式，带元数据 */
export function toJSON(result: QueryResult, sourceName: string = 'query_result'): string {
  const data = result.rows.map((row) => {
    const obj: Record<string, unknown> = {}
    result.columns.forEach((col, i) => {
      obj[col.name] = row[i]
    })
    return obj
  })
  
  const payload = {
    metadata: {
      source: sourceName,
      exportedAt: getTimestamp(),
      rowCount: result.rows.length,
      columns: result.columns.map(c => ({ name: c.name, type: c.dataType }))
    },
    data
  }
  
  return JSON.stringify(payload, null, 2)
}

function escapeSQLValue(value: unknown): string {
  if (value === null || value === undefined) return 'NULL'
  if (typeof value === 'number') return String(value)
  if (typeof value === 'boolean') return value ? '1' : '0'
  return `'${String(value).replace(/'/g, "''")}'`
}

/** 将查询结果转换为专业的 SQL 脚本格式 */
export function toSQL(result: QueryResult, tableName: string = 'exported_table', ddl?: string): string {
  if (result.rows.length === 0) return '-- No data to export'

  const header = [
    '--',
    ` -- DevForge 数据导出脚本`,
    ` -- 目标表: ${tableName}`,
    ` -- 导出时间: ${getTimestamp()}`,
    ` -- 数据行数: ${result.rows.length}`,
    '--',
    'SET NAMES utf8mb4;',
    'SET FOREIGN_KEY_CHECKS = 0;',
    '',
  ].join('\n')

  // 如果有表结构 DDL，插入到 INSERT 语句前
  const ddlSection = ddl
    ? `-- ----------------------------\n-- 表结构 ${tableName}\n-- ----------------------------\nDROP TABLE IF EXISTS \`${tableName}\`;\n${ddl.trim().replace(/;$/, '')};\n\n-- ----------------------------\n-- 数据 ${tableName}\n-- ----------------------------\n`
    : ''

  const colNames = result.columns.map((c) => `\`${c.name}\``).join(', ')
  const inserts = result.rows.map((row) => {
    const values = row.map((v) => escapeSQLValue(v)).join(', ')
    return `INSERT INTO \`${tableName}\` (${colNames}) VALUES (${values});`
  })
  
  const footer = '\n\nSET FOREIGN_KEY_CHECKS = 1;'
  
  return header + ddlSection + inserts.join('\n') + footer
}

/** 将查询结果转换为 Markdown 表格格式，包含统计摘要 */
export function toMarkdown(result: QueryResult, sourceName: string = '数据'): string {
  if (result.columns.length === 0) return ''
  
  const stats = [
    `| 导出项目 | 详情 |`,
    `| :--- | :--- |`,
    `| **数据来源** | \`${sourceName}\` |`,
    `| **导出时间** | ${getTimestamp()} |`,
    `| **总计行数** | ${result.rows.length} rows |`,
    `| **字段数量** | ${result.columns.length} columns |`,
  ].join('\n')

  const title = `## ${sourceName} 导出报告\n\n`
  const summaryHeader = `### 📋 导出概览\n\n${stats}\n\n`
  const dataHeader = `### 🔍 详细数据\n\n`

  // 记录数字列索引，以便右对齐
  const numericIndices = result.columns.reduce((acc, col, idx) => {
    const type = col.dataType.toLowerCase()
    if (['int', 'decimal', 'double', 'float', 'number', 'bigint'].some(t => type.includes(t))) {
      acc.add(idx)
    }
    return acc
  }, new Set<number>())

  // 表头
  const header = '| ' + result.columns.map(c => `**${c.name}**`).join(' | ') + ' |'
  // 分隔行 (处理对齐)
  const separator = '| ' + result.columns.map((_, i) => numericIndices.has(i) ? '---:' : ':---').join(' | ') + ' |'
  
  // 数据行
  const rows = result.rows.map(row =>
    '| ' + row.map((v, i) => {
      if (v === null || v === undefined) return '_NULL_'
      const str = String(v)
      // 处理换行和表格特殊字符
      const formatted = str.replace(/\|/g, '\\|').replace(/\r?\n/g, '<br/>')
      return numericIndices.has(i) ? `\`${formatted}\`` : formatted
    }).join(' | ') + ' |'
  )
  
  const footer = `\n\n---\n*Generated by DevForge at ${new Date().toISOString()}*`
  
  return title + summaryHeader + dataHeader + [header, separator, ...rows].join('\n') + footer
}

export type ExportFormat = 'csv' | 'json' | 'sql' | 'markdown'

/** 根据导出格式返回文件扩展名 */
export function getFileExtension(format: ExportFormat): string {
  switch (format) {
    case 'csv': return 'csv'
    case 'json': return 'json'
    case 'sql': return 'sql'
    case 'markdown': return 'md'
  }
}

/** 根据导出格式返回文件对话框过滤器 */
export function getFilters(format: ExportFormat): { name: string; extensions: string[] }[] {
  switch (format) {
    case 'csv': return [{ name: 'CSV 报表', extensions: ['csv'] }]
    case 'json': return [{ name: 'JSON 数据', extensions: ['json'] }]
    case 'sql': return [{ name: 'SQL 脚本', extensions: ['sql'] }]
    case 'markdown': return [{ name: 'Markdown 文档', extensions: ['md'] }]
  }
}

/** 将查询结果格式化为指定格式的字符串（客户端导出） */
export function formatData(result: QueryResult, format: ExportFormat, name: string = 'exported_data', ddl?: string): string {
  switch (format) {
    case 'csv': return toCSV(result)
    case 'json': return toJSON(result, name)
    case 'sql': return toSQL(result, name, ddl)
    case 'markdown': return toMarkdown(result, name)
  }
}
